runtime: nodejs
env: flex
runtime_config:
  operating_system: 'ubuntu22'

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/gloriayoon301316188:us-west1:cmpt372-project-bestgroup
  DB_PASS: Password123
  APP_ORIGIN: https://gloriayoon301316188.uc.r.appspot.com
  AUTH0_ORIGIN: https://dev-clqbtth7sknk4r0a.us.auth0.com
  AUTH0_CLIENT_ID: 6DF1LPKvK4aHzt0qzEBmQ7PmOXLryy0Q
  AUTH0_CLIENT_SECRET: syBl9I6YxvJ6UUqcGneC7yZ9KDTEgjoxUAd-JhJXVBx5_lrTJPhcKy90blk7qWAt
  AUTH0_MGMT_CLIENT_ID: fyBuCOYopVqRD9AFeC3yOq9ZicqNpXMQ
  AUTH0_MGMT_CLIENT_SECRET: JOLx8FBVm5kiZL0hxfhQUjT3xDP1pBxKecJAqc7P_2mp2Q1ZbsT03IdcTR75RX5S
  GOOGLE_OPERATIONS_RESEARCH_API_KEY: AIzaSyDeP6wErrAQhtBuS9f0bfbmP_Q3csoahys

beta_settings:
  cloud_sql_instances: 'gloriayoon301316188:us-west1:cmpt372-project-bestgroup'

automatic_scaling:
  max_num_instances: 1
