name: Code Quality Checks
on: [pull_request]

permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint with TypeScript
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          tsc_flags: '-b'
      - name: Lint with ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true
          eslint_flags: --report-unused-disable-directives --max-warnings=0 .
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-check
